{
 "title": "Mission Control Overview",
 "tags": [ "mission-control" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active agents",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(country_code) (active_agents)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mission control logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component!=\"\"}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(http_requests_total[5m])" }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "filters": [
      { "id": "17a68cb9", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "mission-control" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 10,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"mission-control\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}